server:
  port: 8090

spring:
  #สพิด
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb??useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  typeAliasesPackage: com.pang.stethoscope.pojo
  mapperLocations: classpath:mabatis/mapper/*.xml
  #configLocation: classpath:/mybatis-config.xml

#showSQL
logging:
  level:
    com:
      root: INFO
      pang:
        stethoscope:
          mapper: DEBUG
